trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'

- script: |
    python -m pip install --upgrade pip
    pip install requests ansible
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  displayName: 'Install dependencies'

- script: |
    ./play.sh
  displayName: 'Executing Ansible playbook'

- script: |
    ./recap.sh ansible.log
  displayName: 'Executing Ansible playbook recap'
